from .manpower import (
    archive_manpower_supplier,
    create_manpower_contact,
    create_manpower_supplier,
    deactivate_manpower_contact,
    restore_manpower_supplier_archive,
    restore_manpower_supplier_trash,
    set_manpower_supplier_status,
    trash_manpower_supplier,
    update_manpower_contact,
    update_manpower_supplier,
)
from .vendors import (
    archive_vendor,
    create_vendor,
    create_vendor_contact,
    deactivate_vendor_contact,
    restore_vendor_archive,
    restore_vendor_trash,
    set_vendor_status,
    trash_vendor,
    update_vendor,
    update_vendor_contact,
)

__all__ = [
    "archive_manpower_supplier",
    "create_manpower_contact",
    "create_manpower_supplier",
    "deactivate_manpower_contact",
    "restore_manpower_supplier_archive",
    "restore_manpower_supplier_trash",
    "set_manpower_supplier_status",
    "trash_manpower_supplier",
    "update_manpower_contact",
    "update_manpower_supplier",
    "archive_vendor",
    "create_vendor",
    "create_vendor_contact",
    "deactivate_vendor_contact",
    "restore_vendor_archive",
    "restore_vendor_trash",
    "set_vendor_status",
    "trash_vendor",
    "update_vendor",
    "update_vendor_contact",
]
