import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("rental_manpower", "0003_rental_timesheets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalAdjustment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateField()),
                ("period_start", models.DateField(db_index=True)),
                ("adjustment_type", models.CharField(choices=[("advance", "Worker Advance"), ("bonus", "Bonus"), ("reimbursement", "Reimbursement"), ("fine", "Fine / Penalty"), ("other_earning", "Other Earning"), ("other_deduction", "Other Deduction")], max_length=24)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(max_length=500)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "Review"), ("approved", "Approved")], db_index=True, default="draft", max_length=16)),
                ("worker_number", models.CharField(max_length=30)),
                ("worker_name", models.CharField(max_length=200)),
                ("supplier_code", models.CharField(max_length=30)),
                ("supplier_name", models.CharField(max_length=200)),
                ("project_code", models.CharField(max_length=30)),
                ("project_name", models.CharField(max_length=220)),
                ("trade", models.CharField(max_length=120)),
                ("rate_type", models.CharField(choices=[("hourly", "Hourly"), ("daily", "Daily"), ("monthly", "Monthly")], max_length=16)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=18)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_adjustments", to="rental_manpower.workerassignment")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rental_manpower_rentaladjustment_records", to="core.company")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rental_settlement_adjustments", to="projects.project")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_adjustments", to="rental_manpower.manpowersupplier")),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_adjustments", to="rental_manpower.rentalworker")),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="submitted_rental_adjustments", to=settings.AUTH_USER_MODEL)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_rental_adjustments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "rental_adjustment", "ordering": ("-transaction_date", "-created_at")},
        ),
        migrations.CreateModel(
            name="SupplierSettlement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("settlement_number", models.CharField(max_length=40)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("source_timesheet_revision", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("draft", "Draft"), ("calculated", "Calculated"), ("review", "Review"), ("approved", "Approved"), ("payment_processing", "Payment Processing"), ("partially_paid", "Partially Paid"), ("paid", "Paid"), ("closed", "Closed")], db_index=True, default="draft", max_length=24)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("calculation_version", models.PositiveSmallIntegerField(default=1)),
                ("source_fingerprint", models.CharField(blank=True, max_length=64)),
                ("snapshot_fingerprint", models.CharField(blank=True, max_length=64)),
                ("project_code", models.CharField(max_length=30)),
                ("project_name", models.CharField(max_length=220)),
                ("supplier_code", models.CharField(max_length=30)),
                ("supplier_name", models.CharField(max_length=200)),
                ("worker_count", models.PositiveIntegerField(default=0)),
                ("total_regular_hours", models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ("total_work_days", models.PositiveIntegerField(default=0)),
                ("total_overtime_hours", models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ("total_base", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_overtime", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_gross", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_adjustment_earnings", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_adjustment_deductions", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_net", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_note", models.CharField(blank=True, max_length=500)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("calculated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="calculated_rental_settlements", to=settings.AUTH_USER_MODEL)),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="submitted_rental_settlements", to=settings.AUTH_USER_MODEL)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_rental_settlements", to=settings.AUTH_USER_MODEL)),
                ("closed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="closed_rental_settlements", to=settings.AUTH_USER_MODEL)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rental_manpower_suppliersettlement_records", to="core.company")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rental_supplier_settlements", to="projects.project")),
                ("source_timesheet", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="supplier_settlements", to="rental_manpower.rentaltimesheetperiod")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="supplier_settlements", to="rental_manpower.manpowersupplier")),
            ],
            options={"db_table": "rental_supplier_settlement", "ordering": ("-period_start", "project_code", "supplier_code")},
        ),
        migrations.CreateModel(
            name="SupplierSettlementLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("worker_number", models.CharField(max_length=30)),
                ("worker_name", models.CharField(max_length=200)),
                ("supplier_code", models.CharField(max_length=30)),
                ("supplier_name", models.CharField(max_length=200)),
                ("project_code", models.CharField(max_length=30)),
                ("project_name", models.CharField(max_length=220)),
                ("trade_summary", models.CharField(max_length=300)),
                ("rate_summary", models.CharField(max_length=500)),
                ("regular_hours", models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ("work_days", models.PositiveIntegerField(default=0)),
                ("overtime_hours", models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ("base_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("overtime_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("gross_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("adjustment_earnings", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("adjustment_deductions", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("net_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rental_manpower_suppliersettlementline_records", to="core.company")),
                ("settlement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="rental_manpower.suppliersettlement")),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_lines", to="rental_manpower.rentalworker")),
            ],
            options={"db_table": "rental_supplier_settlement_line", "ordering": ("worker_number", "worker_name")},
        ),
        migrations.CreateModel(
            name="SupplierSettlementRateLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField()),
                ("trade", models.CharField(max_length=120)),
                ("rate_type", models.CharField(choices=[("hourly", "Hourly"), ("daily", "Daily"), ("monthly", "Monthly")], max_length=16)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=18)),
                ("regular_hours", models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ("billable_days", models.PositiveIntegerField(default=0)),
                ("calendar_days", models.PositiveIntegerField(default=0)),
                ("base_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_rate_lines", to="rental_manpower.workerassignment")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rental_manpower_suppliersettlementrateline_records", to="core.company")),
                ("settlement_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rate_lines", to="rental_manpower.suppliersettlementline")),
            ],
            options={"db_table": "rental_supplier_settlement_rate", "ordering": ("effective_from", "created_at")},
        ),
        migrations.CreateModel(
            name="SupplierSettlementAdjustmentLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adjustment_type", models.CharField(choices=[("advance", "Worker Advance"), ("bonus", "Bonus"), ("reimbursement", "Reimbursement"), ("fine", "Fine / Penalty"), ("other_earning", "Other Earning"), ("other_deduction", "Other Deduction")], max_length=24)),
                ("adjustment_label", models.CharField(max_length=100)),
                ("effect", models.CharField(choices=[("earning", "Adds to supplier payable"), ("deduction", "Deducts from supplier payable")], max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(max_length=500)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("transaction_date", models.DateField()),
                ("adjustment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_snapshot_lines", to="rental_manpower.rentaladjustment")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rental_manpower_suppliersettlementadjustmentline_records", to="core.company")),
                ("settlement_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adjustment_lines", to="rental_manpower.suppliersettlementline")),
            ],
            options={"db_table": "rental_supplier_settlement_adjustment", "ordering": ("transaction_date", "created_at")},
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_number", models.CharField(max_length=40)),
                ("payment_date", models.DateField()),
                ("method", models.CharField(choices=[("bank", "Bank"), ("cash", "Cash"), ("cheque", "Cheque")], max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("status", models.CharField(choices=[("processing", "Processing"), ("paid", "Paid"), ("failed", "Failed"), ("reversed", "Reversed"), ("cancelled", "Cancelled")], db_index=True, default="processing", max_length=16)),
                ("transaction_reference", models.CharField(blank=True, max_length=120)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("result_reason", models.CharField(blank=True, max_length=500)),
                ("supplier_code", models.CharField(max_length=30)),
                ("supplier_name", models.CharField(max_length=200)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rental_manpower_supplierpayment_records", to="core.company")),
                ("retry_of", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="retry_payments", to="rental_manpower.supplierpayment")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="rental_manpower.manpowersupplier")),
            ],
            options={"db_table": "rental_supplier_payment", "ordering": ("-payment_date", "-created_at")},
        ),
        migrations.CreateModel(
            name="SupplierPaymentAllocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rental_manpower_supplierpaymentallocation_records", to="core.company")),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="allocations", to="rental_manpower.supplierpayment")),
                ("settlement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_allocations", to="rental_manpower.suppliersettlement")),
            ],
            options={"db_table": "rental_supplier_payment_allocation", "ordering": ("settlement__period_start", "created_at")},
        ),

        migrations.AddConstraint(model_name="rentaladjustment", constraint=models.CheckConstraint(condition=Q(amount__gt=0), name="rntl_adj_amount_pos_chk")),
        migrations.AddConstraint(model_name="rentaladjustment", constraint=models.CheckConstraint(condition=Q(status__in=["draft", "review", "approved"]), name="rntl_adj_status_chk")),
        migrations.AddConstraint(model_name="rentaladjustment", constraint=models.CheckConstraint(condition=Q(adjustment_type__in=["advance", "bonus", "reimbursement", "fine", "other_earning", "other_deduction"]), name="rntl_adj_type_chk")),
        migrations.AddConstraint(model_name="rentaladjustment", constraint=models.CheckConstraint(condition=Q(rate_type__in=["hourly", "daily", "monthly"]), name="rntl_adj_rate_type_chk")),
        migrations.AddConstraint(model_name="rentaladjustment", constraint=models.UniqueConstraint(condition=~Q(reference=""), fields=("company", "reference"), name="rntl_adj_ref_uniq")),
        migrations.AddIndex(model_name="rentaladjustment", index=models.Index(fields=["company", "period_start", "status"], name="rntl_adj_period_st_idx")),
        migrations.AddIndex(model_name="rentaladjustment", index=models.Index(fields=["company", "worker", "period_start"], name="rntl_adj_worker_per_idx")),
        migrations.AddIndex(model_name="rentaladjustment", index=models.Index(fields=["company", "project", "supplier", "period_start"], name="rntl_adj_scope_per_idx")),

        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.UniqueConstraint(fields=("company", "settlement_number"), name="rntl_set_no_uniq")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.UniqueConstraint(fields=("company", "project", "supplier", "period_start"), name="rntl_set_scope_uniq")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(period_end__gte=models.F("period_start")), name="rntl_set_dates_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(source_timesheet_revision__gte=1), name="rntl_set_ts_rev_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(revision__gte=0), name="rntl_set_rev_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(calculation_version__gte=1), name="rntl_set_calc_ver_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(status__in=["draft", "calculated", "review", "approved", "payment_processing", "partially_paid", "paid", "closed"]), name="rntl_set_status_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(total_regular_hours__gte=0), name="rntl_set_reg_hrs_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(total_overtime_hours__gte=0), name="rntl_set_ot_hrs_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(total_base__gte=0), name="rntl_set_base_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(total_overtime__gte=0), name="rntl_set_ot_amt_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(total_gross__gte=0), name="rntl_set_gross_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(total_adjustment_earnings__gte=0), name="rntl_set_adj_earn_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(total_adjustment_deductions__gte=0), name="rntl_set_adj_ded_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(total_net__gte=0), name="rntl_set_net_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(total_gross=models.F("total_base") + models.F("total_overtime")), name="rntl_set_gross_math_chk")),
        migrations.AddConstraint(model_name="suppliersettlement", constraint=models.CheckConstraint(condition=Q(total_net=models.F("total_gross") + models.F("total_adjustment_earnings") - models.F("total_adjustment_deductions")), name="rntl_set_net_math_chk")),
        migrations.AddIndex(model_name="suppliersettlement", index=models.Index(fields=["company", "period_start", "status"], name="rntl_set_period_st_idx")),
        migrations.AddIndex(model_name="suppliersettlement", index=models.Index(fields=["company", "supplier", "-period_start"], name="rntl_set_supplier_idx")),
        migrations.AddIndex(model_name="suppliersettlement", index=models.Index(fields=["company", "project", "-period_start"], name="rntl_set_project_idx")),

        migrations.AddConstraint(model_name="suppliersettlementline", constraint=models.UniqueConstraint(fields=("settlement", "worker"), name="rntl_set_line_worker_uniq")),
        migrations.AddConstraint(model_name="suppliersettlementline", constraint=models.CheckConstraint(condition=Q(regular_hours__gte=0), name="rntl_set_line_hrs_chk")),
        migrations.AddConstraint(model_name="suppliersettlementline", constraint=models.CheckConstraint(condition=Q(overtime_hours__gte=0), name="rntl_set_line_ot_hrs_chk")),
        migrations.AddConstraint(model_name="suppliersettlementline", constraint=models.CheckConstraint(condition=Q(base_amount__gte=0), name="rntl_set_line_base_chk")),
        migrations.AddConstraint(model_name="suppliersettlementline", constraint=models.CheckConstraint(condition=Q(overtime_amount__gte=0), name="rntl_set_line_ot_amt_chk")),
        migrations.AddConstraint(model_name="suppliersettlementline", constraint=models.CheckConstraint(condition=Q(adjustment_earnings__gte=0), name="rntl_set_line_adj_er_chk")),
        migrations.AddConstraint(model_name="suppliersettlementline", constraint=models.CheckConstraint(condition=Q(adjustment_deductions__gte=0), name="rntl_set_line_adj_dd_chk")),
        migrations.AddConstraint(model_name="suppliersettlementline", constraint=models.CheckConstraint(condition=Q(gross_amount=models.F("base_amount") + models.F("overtime_amount")), name="rntl_set_line_gross_chk")),
        migrations.AddConstraint(model_name="suppliersettlementline", constraint=models.CheckConstraint(condition=Q(net_amount=models.F("gross_amount") + models.F("adjustment_earnings") - models.F("adjustment_deductions")), name="rntl_set_line_net_chk")),
        migrations.AddConstraint(model_name="suppliersettlementline", constraint=models.CheckConstraint(condition=Q(net_amount__gte=0), name="rntl_set_line_net_pos_chk")),
        migrations.AddIndex(model_name="suppliersettlementline", index=models.Index(fields=["company", "settlement", "worker"], name="rntl_set_line_worker_idx")),

        migrations.AddConstraint(model_name="suppliersettlementrateline", constraint=models.UniqueConstraint(fields=("settlement_line", "assignment"), name="rntl_set_rate_asg_uniq")),
        migrations.AddConstraint(model_name="suppliersettlementrateline", constraint=models.CheckConstraint(condition=Q(effective_to__gte=models.F("effective_from")), name="rntl_set_rate_dates_chk")),
        migrations.AddConstraint(model_name="suppliersettlementrateline", constraint=models.CheckConstraint(condition=Q(rate__gt=0), name="rntl_set_rate_pos_chk")),
        migrations.AddConstraint(model_name="suppliersettlementrateline", constraint=models.CheckConstraint(condition=Q(regular_hours__gte=0), name="rntl_set_rate_hrs_chk")),
        migrations.AddConstraint(model_name="suppliersettlementrateline", constraint=models.CheckConstraint(condition=Q(base_amount__gte=0), name="rntl_set_rate_base_chk")),
        migrations.AddIndex(model_name="suppliersettlementrateline", index=models.Index(fields=["company", "settlement_line"], name="rntl_set_rate_line_idx")),

        migrations.AddConstraint(model_name="suppliersettlementadjustmentline", constraint=models.UniqueConstraint(fields=("settlement_line", "adjustment"), name="rntl_set_adj_line_uniq")),
        migrations.AddConstraint(model_name="suppliersettlementadjustmentline", constraint=models.CheckConstraint(condition=Q(amount__gt=0), name="rntl_set_adj_amt_pos_chk")),
        migrations.AddConstraint(model_name="suppliersettlementadjustmentline", constraint=models.CheckConstraint(condition=Q(effect__in=["earning", "deduction"]), name="rntl_set_adj_effect_chk")),
        migrations.AddIndex(model_name="suppliersettlementadjustmentline", index=models.Index(fields=["company", "settlement_line"], name="rntl_set_adj_line_idx")),

        migrations.AddConstraint(model_name="supplierpayment", constraint=models.UniqueConstraint(fields=("company", "payment_number"), name="rntl_pay_no_uniq")),
        migrations.AddConstraint(model_name="supplierpayment", constraint=models.UniqueConstraint(condition=~Q(transaction_reference=""), fields=("company", "transaction_reference"), name="rntl_pay_ref_uniq")),
        migrations.AddConstraint(model_name="supplierpayment", constraint=models.CheckConstraint(condition=Q(amount__gt=0), name="rntl_pay_amount_pos_chk")),
        migrations.AddConstraint(model_name="supplierpayment", constraint=models.CheckConstraint(condition=Q(method__in=["bank", "cash", "cheque"]), name="rntl_pay_method_chk")),
        migrations.AddConstraint(model_name="supplierpayment", constraint=models.CheckConstraint(condition=Q(status__in=["processing", "paid", "failed", "reversed", "cancelled"]), name="rntl_pay_status_chk")),
        migrations.AddConstraint(model_name="supplierpayment", constraint=models.CheckConstraint(condition=~Q(status="paid") | Q(method="cash") | ~Q(transaction_reference=""), name="rntl_pay_paid_ref_chk")),
        migrations.AddConstraint(model_name="supplierpayment", constraint=models.CheckConstraint(condition=~Q(status__in=["failed", "reversed"]) | ~Q(result_reason=""), name="rntl_pay_reason_chk")),
        migrations.AddIndex(model_name="supplierpayment", index=models.Index(fields=["company", "supplier", "-payment_date"], name="rntl_pay_supplier_idx")),
        migrations.AddIndex(model_name="supplierpayment", index=models.Index(fields=["company", "status", "-payment_date"], name="rntl_pay_status_idx")),

        migrations.AddConstraint(model_name="supplierpaymentallocation", constraint=models.UniqueConstraint(fields=("payment", "settlement"), name="rntl_pay_alloc_uniq")),
        migrations.AddConstraint(model_name="supplierpaymentallocation", constraint=models.CheckConstraint(condition=Q(amount__gt=0), name="rntl_pay_alloc_amt_chk")),
        migrations.AddIndex(model_name="supplierpaymentallocation", index=models.Index(fields=["company", "settlement"], name="rntl_pay_alloc_set_idx")),
    ]
