from django.urls import path

from . import views

app_name = "sourcing"

urlpatterns = [
    path("", views.sourcing_home, name="home"),
    path("vendors/", views.vendor_list, name="vendor_list"),
    path("material-finder/", views.material_finder, name="material_finder"),
    path("vendors/new/", views.vendor_create, name="vendor_create"),
    path("vendors/<uuid:vendor_id>/", views.vendor_detail, name="vendor_detail"),
    path("vendors/<uuid:vendor_id>/edit/", views.vendor_edit, name="vendor_edit"),
    path("vendors/<uuid:vendor_id>/status/", views.vendor_status, name="vendor_status"),
    path("vendors/<uuid:vendor_id>/archive/", views.vendor_archive, name="vendor_archive"),
    path("vendors/<uuid:vendor_id>/restore-archive/", views.vendor_restore_archive, name="vendor_restore_archive"),
    path("vendors/<uuid:vendor_id>/trash/", views.vendor_trash, name="vendor_trash"),
    path("vendors/<uuid:vendor_id>/delete/", views.vendor_delete, name="vendor_delete"),
    path("vendors/<uuid:vendor_id>/restore-trash/", views.vendor_restore_trash, name="vendor_restore_trash"),
    path("vendors/<uuid:vendor_id>/contacts/new/", views.vendor_contact_create, name="vendor_contact_create"),
    path("vendors/<uuid:vendor_id>/contacts/<uuid:contact_id>/edit/", views.vendor_contact_edit, name="vendor_contact_edit"),
    path("vendors/<uuid:vendor_id>/contacts/<uuid:contact_id>/deactivate/", views.vendor_contact_deactivate, name="vendor_contact_deactivate"),
    path("vendors/<uuid:vendor_id>/contacts/<uuid:contact_id>/delete/", views.vendor_contact_delete, name="vendor_contact_delete"),
    path("vendors/<uuid:vendor_id>/catalog/new/", views.vendor_offer_create, name="vendor_offer_create"),
    path("vendors/<uuid:vendor_id>/catalog/<uuid:offer_id>/edit/", views.vendor_offer_edit, name="vendor_offer_edit"),
    path("vendors/<uuid:vendor_id>/catalog/<uuid:offer_id>/verify/", views.vendor_offer_verify, name="vendor_offer_verify"),
    path("vendors/<uuid:vendor_id>/catalog/<uuid:offer_id>/history/", views.vendor_offer_history, name="vendor_offer_history"),
    path("vendors/<uuid:vendor_id>/catalog/<uuid:offer_id>/status/", views.vendor_offer_status, name="vendor_offer_status"),
    path("vendors/<uuid:vendor_id>/catalog/<uuid:offer_id>/delete/", views.vendor_offer_delete, name="vendor_offer_delete"),
    path("manpower-suppliers/", views.manpower_supplier_list, name="manpower_supplier_list"),
    path("workforce-finder/", views.workforce_finder, name="workforce_finder"),
    path("data-exchange/", views.data_exchange, name="data_exchange"),
    path("data-exchange/export/<str:dataset>/", views.data_export, name="data_export"),
    path("manpower-suppliers/new/", views.manpower_supplier_create, name="manpower_supplier_create"),
    path("manpower-suppliers/<uuid:supplier_id>/", views.manpower_supplier_detail, name="manpower_supplier_detail"),
    path("manpower-suppliers/<uuid:supplier_id>/edit/", views.manpower_supplier_edit, name="manpower_supplier_edit"),
    path("manpower-suppliers/<uuid:supplier_id>/status/", views.manpower_supplier_status, name="manpower_supplier_status"),
    path("manpower-suppliers/<uuid:supplier_id>/archive/", views.manpower_supplier_archive, name="manpower_supplier_archive"),
    path("manpower-suppliers/<uuid:supplier_id>/restore-archive/", views.manpower_supplier_restore_archive, name="manpower_supplier_restore_archive"),
    path("manpower-suppliers/<uuid:supplier_id>/trash/", views.manpower_supplier_trash, name="manpower_supplier_trash"),
    path("manpower-suppliers/<uuid:supplier_id>/delete/", views.manpower_supplier_delete, name="manpower_supplier_delete"),
    path("manpower-suppliers/<uuid:supplier_id>/restore-trash/", views.manpower_supplier_restore_trash, name="manpower_supplier_restore_trash"),
    path("manpower-suppliers/<uuid:supplier_id>/contacts/new/", views.manpower_contact_create, name="manpower_contact_create"),
    path("manpower-suppliers/<uuid:supplier_id>/contacts/<uuid:contact_id>/edit/", views.manpower_contact_edit, name="manpower_contact_edit"),
    path("manpower-suppliers/<uuid:supplier_id>/contacts/<uuid:contact_id>/deactivate/", views.manpower_contact_deactivate, name="manpower_contact_deactivate"),
    path("manpower-suppliers/<uuid:supplier_id>/contacts/<uuid:contact_id>/delete/", views.manpower_contact_delete, name="manpower_contact_delete"),
    path("manpower-suppliers/<uuid:supplier_id>/workforce/new/", views.workforce_offer_create, name="workforce_offer_create"),
    path("manpower-suppliers/<uuid:supplier_id>/workforce/<uuid:offer_id>/edit/", views.workforce_offer_edit, name="workforce_offer_edit"),
    path("manpower-suppliers/<uuid:supplier_id>/workforce/<uuid:offer_id>/verify/", views.workforce_offer_verify, name="workforce_offer_verify"),
    path("manpower-suppliers/<uuid:supplier_id>/workforce/<uuid:offer_id>/history/", views.workforce_offer_history, name="workforce_offer_history"),
    path("manpower-suppliers/<uuid:supplier_id>/workforce/<uuid:offer_id>/status/", views.workforce_offer_status, name="workforce_offer_status"),
    path("manpower-suppliers/<uuid:supplier_id>/workforce/<uuid:offer_id>/delete/", views.workforce_offer_delete, name="workforce_offer_delete"),
    path("materials/", views.material_list, name="material_list"),
    path("materials/new/", views.material_create, name="material_create"),
    path("materials/<uuid:material_id>/edit/", views.material_edit, name="material_edit"),
    path("materials/<uuid:material_id>/status/", views.material_status, name="material_status"),
    path("materials/<uuid:material_id>/delete/", views.material_delete, name="material_delete"),
    path("trades/", views.trade_list, name="trade_list"),
    path("trades/new/", views.trade_create, name="trade_create"),
    path("trades/<uuid:trade_id>/edit/", views.trade_edit, name="trade_edit"),
    path("trades/<uuid:trade_id>/status/", views.trade_status, name="trade_status"),
    path("trades/<uuid:trade_id>/delete/", views.trade_delete, name="trade_delete"),
]
