# Generated by Django 5.2.17 on 2026-08-17 17:31

import apps.inventory.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockitem_deleted_at_stockitem_deleted_by_and_more'),
        ('projects', '0002_project_deleted_at_project_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('project', 'Project')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('location_type', 'code'),
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('transfer_date', models.DateField()),
                ('document_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='stock-transfers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'jpeg', 'png')), apps.inventory.models.validate_attachment_size])),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('reversed', 'Reversed')], default='completed', editable=False, max_length=20)),
                ('reversal_reason', models.CharField(blank=True, editable=False, max_length=240)),
                ('reversed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-transfer_date', '-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('no_value', 'No value'), ('lost', 'Lost')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('source_condition_snapshot', models.CharField(editable=False, max_length=20)),
                ('unit_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='stockitem',
            name='uniq_stock_identity_per_project',
        ),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='stock_project_status_name_idx',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('no_value', 'No value')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='condition_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location_code_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location_name_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=180),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening stock'), ('addition', 'Stock added'), ('usage', 'Stock used'), ('adjustment_in', 'Positive adjustment'), ('adjustment_out', 'Negative adjustment'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('loss', 'Lost in transfer'), ('reversal', 'Reversal')], max_length=24),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_location', to='projects.project'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.inventorylocation'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['location', 'status', 'material_name'], name='stock_project_status_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('location', 'normalized_material_name', 'normalized_supplier_name', 'normalized_supplier_phone', 'condition'), name='uniq_stock_identity_per_location_condition'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.inventorylocation'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.inventorylocation'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='destination_stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_lines', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='source_stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_lines', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stocktransfer'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transfer_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocktransferline'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['location_code_snapshot'], name='movement_location_snap_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('location_type', 'project'), ('project__isnull', False)), models.Q(('location_type', 'office'), ('project__isnull', True)), _connector='OR'), name='location_type_project_consistent'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['source_location', '-transfer_date'], name='transfer_source_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['destination_location', '-transfer_date'], name='transfer_destination_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_location', models.F('destination_location')), _negated=True), name='transfer_locations_different'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transfer_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination_stock_item__isnull', True), ('outcome', 'lost')), models.Q(models.Q(('outcome', 'lost'), _negated=True), ('destination_stock_item__isnull', False)), _connector='OR'), name='transfer_line_destination_consistent'),
        ),
    ]
