# Generated by Django 5.2.17 on 2026-08-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_backfill_inventory_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='reversal_idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
