# Generated by Django 5.2.17 on 2026-08-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stocktransfer_reversal_idempotency_key'),
        ('projects', '0002_project_deleted_at_project_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylocation',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_location', to='projects.project'),
        ),
    ]
