import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("internal_payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=160)),
                ("category", models.CharField(choices=[("earning", "Earning"), ("deduction", "Deduction")], max_length=20)),
                ("recurrence", models.CharField(choices=[("recurring", "Recurring"), ("variable", "Variable")], max_length=20)),
                ("calculation", models.CharField(choices=[("fixed_amount", "Fixed Amount"), ("manual_amount", "Manual Amount")], max_length=30)),
                ("wps_mapping", models.CharField(choices=[("basic_salary", "Basic Salary"), ("housing_allowance", "Housing Allowance"), ("other_earnings", "Other Earnings"), ("deductions", "Deductions"), ("not_mapped", "Not mapped")], default="not_mapped", max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_salarycomponent_records", to="core.company")),
            ],
            options={"db_table": "internal_salary_component", "ordering": ("category", "code", "name")},
        ),
        migrations.CreateModel(
            name="OvertimePolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=160)),
                ("divisor", models.DecimalField(decimal_places=4, max_digits=18)),
                ("multiplier", models.DecimalField(decimal_places=4, max_digits=18)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("base_component", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="overtime_policies", to="internal_payroll.salarycomponent")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_overtimepolicy_records", to="core.company")),
            ],
            options={"db_table": "internal_overtime_policy", "ordering": ("code", "name")},
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("overtime_policy_code", models.CharField(blank=True, max_length=30)),
                ("overtime_policy_name", models.CharField(blank=True, max_length=160)),
                ("overtime_base_component_code", models.CharField(blank=True, max_length=30)),
                ("overtime_base_component_name", models.CharField(blank=True, max_length=160)),
                ("overtime_divisor", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("overtime_multiplier", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("notes", models.TextField(blank=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_salarystructure_records", to="core.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="salary_structures", to="internal_payroll.internalemployee")),
                ("overtime_policy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="salary_structures", to="internal_payroll.overtimepolicy")),
            ],
            options={"db_table": "internal_salary_structure", "ordering": ("-effective_from", "-created_at")},
        ),
        migrations.CreateModel(
            name="SalaryStructureLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("component_code", models.CharField(max_length=30)),
                ("component_name", models.CharField(max_length=160)),
                ("component_category", models.CharField(choices=[("earning", "Earning"), ("deduction", "Deduction")], max_length=20)),
                ("component_recurrence", models.CharField(choices=[("recurring", "Recurring"), ("variable", "Variable")], max_length=20)),
                ("component_calculation", models.CharField(choices=[("fixed_amount", "Fixed Amount"), ("manual_amount", "Manual Amount")], max_length=30)),
                ("wps_mapping", models.CharField(choices=[("basic_salary", "Basic Salary"), ("housing_allowance", "Housing Allowance"), ("other_earnings", "Other Earnings"), ("deductions", "Deductions"), ("not_mapped", "Not mapped")], max_length=30)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_salarystructureline_records", to="core.company")),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="salary_structure_lines", to="internal_payroll.salarycomponent")),
                ("structure", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="internal_payroll.salarystructure")),
            ],
            options={"db_table": "internal_salary_structure_line", "ordering": ("component_category", "component_code")},
        ),
        migrations.AddConstraint(model_name="salarycomponent", constraint=models.UniqueConstraint(fields=("company", "code"), name="int_sal_comp_company_code_uniq")),
        migrations.AddConstraint(model_name="salarycomponent", constraint=models.UniqueConstraint(fields=("company", "name"), name="int_sal_comp_company_name_uniq")),
        migrations.AddConstraint(model_name="salarycomponent", constraint=models.CheckConstraint(condition=Q(category__in=["earning", "deduction"]), name="int_sal_comp_category_valid")),
        migrations.AddConstraint(model_name="salarycomponent", constraint=models.CheckConstraint(condition=Q(recurrence__in=["recurring", "variable"]), name="int_sal_comp_recur_valid")),
        migrations.AddConstraint(model_name="salarycomponent", constraint=models.CheckConstraint(condition=Q(calculation__in=["fixed_amount", "manual_amount"]), name="int_sal_comp_calc_valid")),
        migrations.AddConstraint(model_name="salarycomponent", constraint=models.CheckConstraint(condition=Q(wps_mapping__in=["basic_salary", "housing_allowance", "other_earnings", "deductions", "not_mapped"]), name="int_sal_comp_wps_valid")),
        migrations.AddConstraint(model_name="salarycomponent", constraint=models.UniqueConstraint(condition=Q(is_active=True, wps_mapping="basic_salary"), fields=("company",), name="int_sal_comp_one_active_basic")),
        migrations.AddIndex(model_name="salarycomponent", index=models.Index(fields=["company", "is_active", "category"], name="int_sal_comp_active_idx")),
        migrations.AddIndex(model_name="salarycomponent", index=models.Index(fields=["company", "wps_mapping"], name="int_sal_comp_wps_idx")),
        migrations.AddConstraint(model_name="overtimepolicy", constraint=models.UniqueConstraint(fields=("company", "code"), name="int_ot_pol_company_code_uniq")),
        migrations.AddConstraint(model_name="overtimepolicy", constraint=models.UniqueConstraint(fields=("company", "name"), name="int_ot_pol_company_name_uniq")),
        migrations.AddConstraint(model_name="overtimepolicy", constraint=models.CheckConstraint(condition=Q(divisor__gt=0), name="int_ot_pol_divisor_positive")),
        migrations.AddConstraint(model_name="overtimepolicy", constraint=models.CheckConstraint(condition=Q(multiplier__gt=0), name="int_ot_pol_multiplier_positive")),
        migrations.AddIndex(model_name="overtimepolicy", index=models.Index(fields=["company", "is_active", "name"], name="int_ot_policy_active_idx")),
        migrations.AddConstraint(model_name="salarystructure", constraint=models.UniqueConstraint(fields=("employee", "effective_from"), name="int_sal_struct_emp_date_uniq")),
        migrations.AddConstraint(model_name="salarystructure", constraint=models.CheckConstraint(condition=Q(effective_to__isnull=True) | Q(effective_to__gte=models.F("effective_from")), name="int_sal_struct_valid_range")),
        migrations.AddConstraint(model_name="salarystructure", constraint=models.UniqueConstraint(condition=Q(effective_to__isnull=True), fields=("employee",), name="int_sal_struct_one_open")),
        migrations.AddIndex(model_name="salarystructure", index=models.Index(fields=["company", "employee", "-effective_from"], name="int_sal_struct_emp_idx")),
        migrations.AddIndex(model_name="salarystructure", index=models.Index(fields=["company", "effective_from", "effective_to"], name="int_sal_struct_dates_idx")),
        migrations.AddConstraint(model_name="salarystructureline", constraint=models.UniqueConstraint(fields=("structure", "component"), name="int_sal_line_struct_comp_uniq")),
        migrations.AddConstraint(model_name="salarystructureline", constraint=models.CheckConstraint(condition=Q(amount__gte=0), name="int_sal_line_amount_nonneg")),
        migrations.AddConstraint(model_name="salarystructureline", constraint=models.CheckConstraint(condition=Q(component_category__in=["earning", "deduction"]), name="int_sal_line_cat_valid")),
        migrations.AddConstraint(model_name="salarystructureline", constraint=models.CheckConstraint(condition=Q(component_recurrence__in=["recurring", "variable"]), name="int_sal_line_recur_valid")),
        migrations.AddConstraint(model_name="salarystructureline", constraint=models.CheckConstraint(condition=Q(component_calculation__in=["fixed_amount", "manual_amount"]), name="int_sal_line_calc_valid")),
        migrations.AddConstraint(model_name="salarystructureline", constraint=models.CheckConstraint(condition=Q(wps_mapping__in=["basic_salary", "housing_allowance", "other_earnings", "deductions", "not_mapped"]), name="int_sal_line_wps_valid")),
        migrations.AddIndex(model_name="salarystructureline", index=models.Index(fields=["company", "structure"], name="int_sal_line_struct_idx")),
        migrations.AddIndex(model_name="salarystructureline", index=models.Index(fields=["company", "component"], name="int_sal_line_component_idx")),
    ]
