import decimal
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("internal_payroll", "0003_attendance_overtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalPayrollPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proration_method", models.CharField(choices=[("not_configured", "Not configured"), ("calendar_days", "Calendar days"), ("no_proration", "No proration")], default="not_configured", max_length=24)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_internalpayrollpolicy_records", to="core.company")),
            ],
            options={"db_table": "internal_payroll_policy"},
        ),
        migrations.CreateModel(
            name="PayrollAdjustment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateField()),
                ("period_start", models.DateField(db_index=True)),
                ("adjustment_type", models.CharField(choices=[("salary_advance", "Salary Advance"), ("advance_recovery", "Advance Recovery"), ("bonus", "Bonus"), ("reimbursement", "Reimbursement"), ("fine", "Fine / Penalty"), ("other_earning", "Other Earning"), ("other_deduction", "Other Deduction")], max_length=32)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(max_length=500)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("recovery_plan", models.CharField(blank=True, max_length=200)),
                ("installment_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("recovery_start", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "Review"), ("approved", "Approved")], db_index=True, default="draft", max_length=16)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_internal_payroll_adjustments", to=settings.AUTH_USER_MODEL)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_payrolladjustment_records", to="core.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_adjustments", to="internal_payroll.internalemployee")),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="submitted_internal_payroll_adjustments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "internal_payroll_adjustment", "ordering": ("-transaction_date", "-created_at")},
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("attendance_revision", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("calculated", "Calculated"), ("review", "Review"), ("approved", "Approved"), ("payment_processing", "Payment Processing"), ("paid", "Paid"), ("closed", "Closed")], db_index=True, default="draft", max_length=24)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("calculation_version", models.PositiveSmallIntegerField(default=1)),
                ("source_fingerprint", models.CharField(blank=True, max_length=64)),
                ("snapshot_fingerprint", models.CharField(blank=True, max_length=64)),
                ("employee_count", models.PositiveIntegerField(default=0)),
                ("total_basic", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("total_allowances", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("total_overtime", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("total_other_earnings", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("total_gross", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("total_advance_recovery", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("total_other_deductions", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("total_deductions", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("total_net", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_note", models.TextField(blank=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_internal_payroll_runs", to=settings.AUTH_USER_MODEL)),
                ("attendance_period", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payroll_runs", to="internal_payroll.attendanceperiod")),
                ("calculated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="calculated_internal_payroll_runs", to=settings.AUTH_USER_MODEL)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_payrollrun_records", to="core.company")),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="submitted_internal_payroll_runs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "internal_payroll_run", "ordering": ("-period_start",)},
        ),
        migrations.CreateModel(
            name="PayrollRunLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_number", models.CharField(max_length=40)),
                ("employee_name", models.CharField(max_length=200)),
                ("branch_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("branch_code", models.CharField(blank=True, max_length=30)),
                ("branch_name", models.CharField(blank=True, max_length=160)),
                ("department_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("department_code", models.CharField(blank=True, max_length=30)),
                ("department_name", models.CharField(blank=True, max_length=160)),
                ("position", models.CharField(blank=True, max_length=160)),
                ("regular_hours", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=9)),
                ("absent_days", models.PositiveSmallIntegerField(default=0)),
                ("leave_days", models.PositiveSmallIntegerField(default=0)),
                ("sick_days", models.PositiveSmallIntegerField(default=0)),
                ("holiday_days", models.PositiveSmallIntegerField(default=0)),
                ("off_days", models.PositiveSmallIntegerField(default=0)),
                ("overtime_hours", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=9)),
                ("overtime_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("overtime_policy_code", models.CharField(blank=True, max_length=30)),
                ("overtime_policy_name", models.CharField(blank=True, max_length=160)),
                ("overtime_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("basic", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("allowances", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("other_earnings", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("gross", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("advance_recovery", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("other_deductions", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("total_deductions", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("net", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_payrollrunline_records", to="core.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_run_lines", to="internal_payroll.internalemployee")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="internal_payroll.payrollrun")),
            ],
            options={"db_table": "internal_payroll_run_line", "ordering": ("employee_number", "employee_name")},
        ),
        migrations.CreateModel(
            name="PayrollRunLineComponent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("component_code", models.CharField(max_length=30)),
                ("component_name", models.CharField(max_length=160)),
                ("component_category", models.CharField(choices=[("earning", "Earning"), ("deduction", "Deduction")], max_length=20)),
                ("component_recurrence", models.CharField(choices=[("recurring", "Recurring"), ("variable", "Variable")], max_length=20)),
                ("component_calculation", models.CharField(choices=[("fixed_amount", "Fixed Amount"), ("manual_amount", "Manual Amount")], max_length=30)),
                ("wps_mapping", models.CharField(choices=[("basic_salary", "Basic Salary"), ("housing_allowance", "Housing Allowance"), ("other_earnings", "Other Earnings"), ("deductions", "Deductions"), ("not_mapped", "Not mapped")], max_length=30)),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField()),
                ("proration_days", models.PositiveSmallIntegerField()),
                ("proration_denominator", models.PositiveSmallIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_payrollrunlinecomponent_records", to="core.company")),
                ("run_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="components", to="internal_payroll.payrollrunline")),
                ("salary_structure", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_line_components", to="internal_payroll.salarystructure")),
                ("salary_structure_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_line_components", to="internal_payroll.salarystructureline")),
            ],
            options={"db_table": "internal_payroll_run_line_component", "ordering": ("component_category", "component_code", "effective_from")},
        ),
        migrations.CreateModel(
            name="PayrollRunLineAdjustment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adjustment_type", models.CharField(max_length=32)),
                ("adjustment_label", models.CharField(max_length=100)),
                ("transaction_date", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("reason", models.CharField(max_length=500)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("effect", models.CharField(choices=[("earning", "Earning"), ("deduction", "Deduction"), ("advance_recovery", "Advance Recovery")], max_length=24)),
                ("adjustment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_line_snapshots", to="internal_payroll.payrolladjustment")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_payrollrunlineadjustment_records", to="core.company")),
                ("run_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adjustments", to="internal_payroll.payrollrunline")),
            ],
            options={"db_table": "internal_payroll_run_line_adjustment", "ordering": ("transaction_date", "created_at")},
        ),
        migrations.AddConstraint(model_name="internalpayrollpolicy", constraint=models.UniqueConstraint(fields=("company",), name="int_pay_policy_company_uniq")),
        migrations.AddConstraint(model_name="internalpayrollpolicy", constraint=models.CheckConstraint(condition=Q(proration_method__in=["not_configured", "calendar_days", "no_proration"]), name="int_pay_policy_proration_valid")),
        migrations.AddConstraint(model_name="payrolladjustment", constraint=models.CheckConstraint(condition=Q(amount__gt=0), name="int_pay_adj_amount_positive")),
        migrations.AddConstraint(model_name="payrolladjustment", constraint=models.CheckConstraint(condition=Q(status__in=["draft", "review", "approved"]), name="int_pay_adj_status_valid")),
        migrations.AddConstraint(model_name="payrolladjustment", constraint=models.CheckConstraint(condition=Q(adjustment_type__in=["salary_advance", "advance_recovery", "bonus", "reimbursement", "fine", "other_earning", "other_deduction"]), name="int_pay_adj_type_valid")),
        migrations.AddConstraint(model_name="payrolladjustment", constraint=models.CheckConstraint(condition=Q(installment_amount__isnull=True) | Q(installment_amount__gt=0), name="int_pay_adj_installment_positive")),
        migrations.AddConstraint(model_name="payrolladjustment", constraint=models.CheckConstraint(condition=Q(installment_amount__isnull=True) | Q(installment_amount__lte=models.F("amount")), name="int_pay_adj_installment_lte_amount")),
        migrations.AddConstraint(model_name="payrolladjustment", constraint=models.CheckConstraint(condition=Q(recovery_start__isnull=True) | Q(recovery_start__gte=models.F("transaction_date")), name="int_pay_adj_recovery_after_txn")),
        migrations.AddConstraint(model_name="payrolladjustment", constraint=models.CheckConstraint(condition=Q(adjustment_type="salary_advance") | (Q(recovery_start__isnull=True) & Q(installment_amount__isnull=True) & Q(recovery_plan="")), name="int_pay_adj_schedule_advance_only")),
        migrations.AddConstraint(model_name="payrolladjustment", constraint=models.UniqueConstraint(condition=~Q(reference=""), fields=("company", "reference"), name="int_pay_adj_company_ref_uniq")),
        migrations.AddIndex(model_name="payrolladjustment", index=models.Index(fields=["company", "period_start", "status"], name="int_pay_adj_period_status_idx")),
        migrations.AddIndex(model_name="payrolladjustment", index=models.Index(fields=["company", "employee", "period_start"], name="int_pay_adj_emp_period_idx")),
        migrations.AddIndex(model_name="payrolladjustment", index=models.Index(fields=["company", "employee", "adjustment_type", "status"], name="int_pay_adj_balance_idx")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.UniqueConstraint(fields=("company", "period_start"), name="int_pay_run_company_period_uniq")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(period_end__gte=models.F("period_start")), name="int_pay_run_valid_range")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(revision__gte=0), name="int_pay_run_revision_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(attendance_revision__gte=0), name="int_pay_run_att_rev_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(status__in=["draft", "calculated", "review", "approved", "payment_processing", "paid", "closed"]), name="int_pay_run_status_valid")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_basic__gte=0), name="int_pay_run_basic_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_allowances__gte=0), name="int_pay_run_allow_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_overtime__gte=0), name="int_pay_run_ot_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_other_earnings__gte=0), name="int_pay_run_other_earn_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_gross__gte=0), name="int_pay_run_gross_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_advance_recovery__gte=0), name="int_pay_run_adv_rec_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_other_deductions__gte=0), name="int_pay_run_other_ded_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_deductions__gte=0), name="int_pay_run_deductions_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_net__gte=0), name="int_pay_run_net_nonneg")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_gross=models.F("total_basic") + models.F("total_allowances") + models.F("total_overtime") + models.F("total_other_earnings")), name="int_pay_run_gross_math")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_deductions=models.F("total_advance_recovery") + models.F("total_other_deductions")), name="int_pay_run_ded_math")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=Q(total_net=models.F("total_gross") - models.F("total_deductions")), name="int_pay_run_net_math")),
        migrations.AddIndex(model_name="payrollrun", index=models.Index(fields=["company", "status", "-period_start"], name="int_pay_run_status_idx")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.UniqueConstraint(fields=("run", "employee"), name="int_pay_line_run_emp_uniq")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(regular_hours__gte=0), name="int_pay_line_hours_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(overtime_hours__gte=0), name="int_pay_line_ot_hours_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(overtime_amount__gte=0), name="int_pay_line_ot_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(basic__gte=0), name="int_pay_line_basic_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(allowances__gte=0), name="int_pay_line_allow_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(other_earnings__gte=0), name="int_pay_line_other_earn_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(gross__gte=0), name="int_pay_line_gross_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(advance_recovery__gte=0), name="int_pay_line_adv_rec_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(other_deductions__gte=0), name="int_pay_line_other_ded_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(total_deductions__gte=0), name="int_pay_line_ded_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(net__gte=0), name="int_pay_line_net_nonneg")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(gross=models.F("basic") + models.F("allowances") + models.F("overtime_amount") + models.F("other_earnings")), name="int_pay_line_gross_math")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(total_deductions=models.F("advance_recovery") + models.F("other_deductions")), name="int_pay_line_ded_math")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=Q(net=models.F("gross") - models.F("total_deductions")), name="int_pay_line_net_math")),
        migrations.AddIndex(model_name="payrollrunline", index=models.Index(fields=["company", "run", "employee_number"], name="int_pay_line_run_emp_idx")),
        migrations.AddIndex(model_name="payrollrunline", index=models.Index(fields=["company", "branch_id_snapshot"], name="int_pay_line_branch_idx")),
        migrations.AddIndex(model_name="payrollrunline", index=models.Index(fields=["company", "department_id_snapshot"], name="int_pay_line_dept_idx")),
        migrations.AddConstraint(model_name="payrollrunlinecomponent", constraint=models.UniqueConstraint(fields=("run_line", "salary_structure_line", "effective_from", "effective_to"), name="int_pay_comp_snapshot_uniq")),
        migrations.AddConstraint(model_name="payrollrunlinecomponent", constraint=models.CheckConstraint(condition=Q(base_amount__gte=0), name="int_pay_comp_base_nonneg")),
        migrations.AddConstraint(model_name="payrollrunlinecomponent", constraint=models.CheckConstraint(condition=Q(amount__gte=0), name="int_pay_comp_amount_nonneg")),
        migrations.AddConstraint(model_name="payrollrunlinecomponent", constraint=models.CheckConstraint(condition=Q(proration_days__gt=0), name="int_pay_comp_days_positive")),
        migrations.AddConstraint(model_name="payrollrunlinecomponent", constraint=models.CheckConstraint(condition=Q(proration_denominator__gt=0), name="int_pay_comp_denom_positive")),
        migrations.AddConstraint(model_name="payrollrunlinecomponent", constraint=models.CheckConstraint(condition=Q(effective_to__gte=models.F("effective_from")), name="int_pay_comp_date_range")),
        migrations.AddConstraint(model_name="payrollrunlinecomponent", constraint=models.CheckConstraint(condition=Q(component_category__in=["earning", "deduction"]), name="int_pay_comp_category_valid")),
        migrations.AddConstraint(model_name="payrollrunlinecomponent", constraint=models.CheckConstraint(condition=Q(component_recurrence__in=["recurring", "variable"]), name="int_pay_comp_recur_valid")),
        migrations.AddConstraint(model_name="payrollrunlinecomponent", constraint=models.CheckConstraint(condition=Q(component_calculation__in=["fixed_amount", "manual_amount"]), name="int_pay_comp_calc_valid")),
        migrations.AddConstraint(model_name="payrollrunlinecomponent", constraint=models.CheckConstraint(condition=Q(wps_mapping__in=["basic_salary", "housing_allowance", "other_earnings", "deductions", "not_mapped"]), name="int_pay_comp_wps_valid")),
        migrations.AddIndex(model_name="payrollrunlinecomponent", index=models.Index(fields=["company", "run_line"], name="int_pay_comp_line_idx")),
        migrations.AddConstraint(model_name="payrollrunlineadjustment", constraint=models.UniqueConstraint(fields=("run_line", "adjustment"), name="int_pay_line_adj_uniq")),
        migrations.AddConstraint(model_name="payrollrunlineadjustment", constraint=models.CheckConstraint(condition=Q(amount__gt=0), name="int_pay_line_adj_amount_positive")),
        migrations.AddConstraint(model_name="payrollrunlineadjustment", constraint=models.CheckConstraint(condition=Q(effect__in=["earning", "deduction", "advance_recovery"]), name="int_pay_line_adj_effect_valid")),
        migrations.AddIndex(model_name="payrollrunlineadjustment", index=models.Index(fields=["company", "run_line"], name="int_pay_line_adj_idx")),
    ]
