import decimal
import uuid

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("internal_payroll", "0004_payroll_engine"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySalaryPaymentSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employer_identifier", models.CharField(blank=True, max_length=100)),
                ("employer_bank_name", models.CharField(blank=True, max_length=160)),
                ("employer_bank_code", models.CharField(blank=True, max_length=40)),
                ("employer_iban", apps.core.fields.EncryptedTextField(blank=True)),
                ("bank_customer_reference", models.CharField(blank=True, max_length=100)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_companysalarypaymentsettings_records", to="core.company")),
            ],
            options={"db_table": "internal_salary_payment_settings"},
        ),
        migrations.CreateModel(
            name="EmployeePaymentProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("destination_type", models.CharField(choices=[("iban", "Bank account / IBAN"), ("salary_card", "Salary card")], default="iban", max_length=20)),
                ("account_holder_name", models.CharField(max_length=200)),
                ("bank_name", models.CharField(max_length=160)),
                ("bank_code", models.CharField(blank=True, max_length=40)),
                ("iban", apps.core.fields.EncryptedTextField(blank=True)),
                ("iban_fingerprint", models.CharField(blank=True, db_index=True, max_length=64)),
                ("salary_card_number", apps.core.fields.EncryptedTextField(blank=True)),
                ("salary_card_fingerprint", models.CharField(blank=True, db_index=True, max_length=64)),
                ("wps_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_employeepaymentprofile_records", to="core.company")),
                ("employee", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="payment_profile", to="internal_payroll.internalemployee")),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="verified_salary_payment_profiles", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "internal_employee_payment_profile"},
        ),
        migrations.CreateModel(
            name="BankExportTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=160)),
                ("channel", models.CharField(choices=[("bank_csv", "Bank CSV"), ("wps", "WPS wage data")], default="bank_csv", max_length=20)),
                ("delimiter", models.CharField(choices=[("comma", "Comma"), ("tab", "Tab"), ("semicolon", "Semicolon")], default="comma", max_length=16)),
                ("encoding", models.CharField(choices=[("utf-8", "UTF-8"), ("utf-8-sig", "UTF-8 with BOM")], default="utf-8", max_length=16)),
                ("include_header", models.BooleanField(default=True)),
                ("columns", models.JSONField(default=list)),
                ("headers", models.JSONField(default=list)),
                ("result_columns", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_bankexporttemplate_records", to="core.company")),
            ],
            options={"db_table": "internal_bank_export_template", "ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="SalaryPaymentBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=60)),
                ("channel", models.CharField(choices=[("bank_csv", "Bank CSV"), ("wps", "WPS wage data")], max_length=20)),
                ("template_code", models.CharField(max_length=40)),
                ("template_name", models.CharField(max_length=160)),
                ("delimiter", models.CharField(choices=[("comma", "Comma"), ("tab", "Tab"), ("semicolon", "Semicolon")], max_length=16)),
                ("encoding", models.CharField(choices=[("utf-8", "UTF-8"), ("utf-8-sig", "UTF-8 with BOM")], max_length=16)),
                ("include_header", models.BooleanField(default=True)),
                ("columns", models.JSONField(default=list)),
                ("headers", models.JSONField(default=list)),
                ("result_columns", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("prepared", "Prepared"), ("exported", "Exported"), ("processing", "Processing"), ("partially_paid", "Partially Paid"), ("attention", "Needs Attention"), ("paid", "Paid"), ("closed", "Closed"), ("cancelled", "Cancelled")], db_index=True, default="prepared", max_length=24)),
                ("employee_count", models.PositiveIntegerField(default=0)),
                ("total_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("paid_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("last_export_sha256", models.CharField(blank=True, max_length=64)),
                ("employer_identifier", models.CharField(blank=True, max_length=100)),
                ("employer_bank_name", models.CharField(blank=True, max_length=160)),
                ("employer_bank_code", models.CharField(blank=True, max_length=40)),
                ("employer_iban", apps.core.fields.EncryptedTextField(blank=True)),
                ("bank_customer_reference", models.CharField(blank=True, max_length=100)),
                ("prepared_at", models.DateTimeField()),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("closed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="closed_salary_payment_batches", to=settings.AUTH_USER_MODEL)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_salarypaymentbatch_records", to="core.company")),
                ("export_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payment_batches", to="internal_payroll.bankexporttemplate")),
                ("exported_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="exported_salary_payment_batches", to=settings.AUTH_USER_MODEL)),
                ("prepared_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prepared_salary_payment_batches", to=settings.AUTH_USER_MODEL)),
                ("processing_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processing_salary_payment_batches", to=settings.AUTH_USER_MODEL)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_batches", to="internal_payroll.payrollrun")),
            ],
            options={"db_table": "internal_salary_payment_batch", "ordering": ("-prepared_at",)},
        ),
        migrations.CreateModel(
            name="SalaryPaymentRow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_active", models.BooleanField(db_index=True, default=True)),
                ("employee_number", models.CharField(max_length=40)),
                ("employee_name", models.CharField(max_length=200)),
                ("national_id", models.CharField(max_length=50)),
                ("destination_type", models.CharField(choices=[("iban", "Bank account / IBAN"), ("salary_card", "Salary card")], max_length=20)),
                ("account_holder_name", models.CharField(max_length=200)),
                ("bank_name", models.CharField(max_length=160)),
                ("bank_code", models.CharField(blank=True, max_length=40)),
                ("iban", apps.core.fields.EncryptedTextField(blank=True)),
                ("salary_card_number", apps.core.fields.EncryptedTextField(blank=True)),
                ("destination_fingerprint", models.CharField(blank=True, max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("basic_salary", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("housing_allowance", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("other_earnings", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("deductions", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("paid", "Paid"), ("failed", "Failed"), ("reversed", "Reversed"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=20)),
                ("transaction_reference", models.CharField(blank=True, max_length=120)),
                ("failure_reason", models.CharField(blank=True, max_length=500)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("last_result_at", models.DateTimeField(blank=True, null=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rows", to="internal_payroll.salarypaymentbatch")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_salarypaymentrow_records", to="core.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="salary_payment_rows", to="internal_payroll.internalemployee")),
                ("run_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_rows", to="internal_payroll.payrollrunline")),
            ],
            options={"db_table": "internal_salary_payment_row", "ordering": ("employee_number",)},
        ),
        migrations.CreateModel(
            name="SalaryPaymentAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("processing", "Processing"), ("paid", "Paid"), ("failed", "Failed"), ("reversed", "Reversed")], default="processing", max_length=20)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_reference", models.CharField(blank=True, max_length=120)),
                ("failure_reason", models.CharField(blank=True, max_length=500)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_salarypaymentattempt_records", to="core.company")),
                ("row", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attempts", to="internal_payroll.salarypaymentrow")),
                ("started_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="started_salary_payment_attempts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "internal_salary_payment_attempt", "ordering": ("attempt_number",)},
        ),
        migrations.CreateModel(
            name="SalaryPaymentResultImport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=255)),
                ("content_sha256", models.CharField(max_length=64)),
                ("updated_rows", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("imported_at", models.DateTimeField()),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="result_imports", to="internal_payroll.salarypaymentbatch")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="internal_payroll_salarypaymentresultimport_records", to="core.company")),
                ("imported_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="salary_payment_result_imports", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "internal_salary_payment_result_import", "ordering": ("-imported_at",)},
        ),
        migrations.AddConstraint(model_name="companysalarypaymentsettings", constraint=models.UniqueConstraint(fields=("company",), name="int_pay_settings_company_uniq")),
        migrations.AddConstraint(model_name="employeepaymentprofile", constraint=models.UniqueConstraint(condition=~Q(iban_fingerprint=""), fields=("company", "iban_fingerprint"), name="int_pay_profile_company_iban_uniq")),
        migrations.AddConstraint(model_name="employeepaymentprofile", constraint=models.UniqueConstraint(condition=~Q(salary_card_fingerprint=""), fields=("company", "salary_card_fingerprint"), name="int_pay_profile_company_card_uniq")),
        migrations.AddConstraint(model_name="employeepaymentprofile", constraint=models.CheckConstraint(condition=Q(destination_type__in=["iban", "salary_card"]), name="int_pay_profile_destination_valid")),
        migrations.AddConstraint(model_name="employeepaymentprofile", constraint=models.CheckConstraint(condition=(Q(destination_type="iban") & ~Q(iban_fingerprint="") & Q(salary_card_fingerprint="")) | (Q(destination_type="salary_card") & Q(iban_fingerprint="") & ~Q(salary_card_fingerprint="")), name="int_pay_profile_destination_fields")),
        migrations.AddIndex(model_name="employeepaymentprofile", index=models.Index(fields=["company", "is_active", "bank_name"], name="int_pay_profile_active_idx")),
        migrations.AddConstraint(model_name="bankexporttemplate", constraint=models.UniqueConstraint(fields=("company", "code"), name="int_bank_template_company_code_uniq")),
        migrations.AddConstraint(model_name="bankexporttemplate", constraint=models.UniqueConstraint(fields=("company", "name"), name="int_bank_template_company_name_uniq")),
        migrations.AddConstraint(model_name="bankexporttemplate", constraint=models.CheckConstraint(condition=Q(channel__in=["bank_csv", "wps"]), name="int_bank_template_channel_valid")),
        migrations.AddConstraint(model_name="bankexporttemplate", constraint=models.CheckConstraint(condition=Q(delimiter__in=["comma", "tab", "semicolon"]), name="int_bank_template_delim_valid")),
        migrations.AddConstraint(model_name="bankexporttemplate", constraint=models.CheckConstraint(condition=Q(encoding__in=["utf-8", "utf-8-sig"]), name="int_bank_template_encoding_valid")),
        migrations.AddIndex(model_name="bankexporttemplate", index=models.Index(fields=["company", "channel", "is_active"], name="int_bank_template_active_idx")),
        migrations.AddConstraint(model_name="salarypaymentbatch", constraint=models.UniqueConstraint(fields=("company", "reference"), name="int_pay_batch_company_ref_uniq")),
        migrations.AddConstraint(model_name="salarypaymentbatch", constraint=models.CheckConstraint(condition=Q(employee_count__gte=0), name="int_pay_batch_employee_count_nonneg")),
        migrations.AddConstraint(model_name="salarypaymentbatch", constraint=models.CheckConstraint(condition=Q(total_amount__gte=0), name="int_pay_batch_total_nonneg")),
        migrations.AddConstraint(model_name="salarypaymentbatch", constraint=models.CheckConstraint(condition=Q(paid_amount__gte=0), name="int_pay_batch_paid_nonneg")),
        migrations.AddConstraint(model_name="salarypaymentbatch", constraint=models.CheckConstraint(condition=Q(paid_amount__lte=models.F("total_amount")), name="int_pay_batch_paid_lte_total")),
        migrations.AddConstraint(model_name="salarypaymentbatch", constraint=models.CheckConstraint(condition=Q(status__in=["prepared", "exported", "processing", "partially_paid", "attention", "paid", "closed", "cancelled"]), name="int_pay_batch_status_valid")),
        migrations.AddConstraint(model_name="salarypaymentbatch", constraint=models.CheckConstraint(condition=Q(channel__in=["bank_csv", "wps"]), name="int_pay_batch_channel_valid")),
        migrations.AddIndex(model_name="salarypaymentbatch", index=models.Index(fields=["company", "run", "status"], name="int_pay_batch_run_status_idx")),
        migrations.AddIndex(model_name="salarypaymentbatch", index=models.Index(fields=["company", "channel", "-prepared_at"], name="int_pay_batch_channel_idx")),
        migrations.AddConstraint(model_name="salarypaymentrow", constraint=models.UniqueConstraint(fields=("batch", "run_line"), name="int_pay_row_batch_line_uniq")),
        migrations.AddConstraint(model_name="salarypaymentrow", constraint=models.UniqueConstraint(condition=Q(claim_active=True), fields=("run_line",), name="int_pay_row_active_line_uniq")),
        migrations.AddConstraint(model_name="salarypaymentrow", constraint=models.CheckConstraint(condition=Q(amount__gt=0), name="int_pay_row_amount_positive")),
        migrations.AddConstraint(model_name="salarypaymentrow", constraint=models.CheckConstraint(condition=Q(basic_salary__gte=0), name="int_pay_row_basic_nonneg")),
        migrations.AddConstraint(model_name="salarypaymentrow", constraint=models.CheckConstraint(condition=Q(housing_allowance__gte=0), name="int_pay_row_housing_nonneg")),
        migrations.AddConstraint(model_name="salarypaymentrow", constraint=models.CheckConstraint(condition=Q(other_earnings__gte=0), name="int_pay_row_other_earn_nonneg")),
        migrations.AddConstraint(model_name="salarypaymentrow", constraint=models.CheckConstraint(condition=Q(deductions__gte=0), name="int_pay_row_deductions_nonneg")),
        migrations.AddConstraint(model_name="salarypaymentrow", constraint=models.CheckConstraint(condition=Q(attempt_count__gte=0), name="int_pay_row_attempt_nonneg")),
        migrations.AddConstraint(model_name="salarypaymentrow", constraint=models.CheckConstraint(condition=Q(status__in=["pending", "processing", "paid", "failed", "reversed", "cancelled"]), name="int_pay_row_status_valid")),
        migrations.AddConstraint(model_name="salarypaymentrow", constraint=models.CheckConstraint(condition=(Q(destination_type="iban") & ~Q(destination_fingerprint="")) | (Q(destination_type="salary_card") & ~Q(destination_fingerprint="")), name="int_pay_row_destination_fields")),
        migrations.AddIndex(model_name="salarypaymentrow", index=models.Index(fields=["company", "batch", "status"], name="int_pay_row_batch_status_idx")),
        migrations.AddIndex(model_name="salarypaymentrow", index=models.Index(fields=["company", "employee", "-created_at"], name="int_pay_row_employee_idx")),
        migrations.AddConstraint(model_name="salarypaymentattempt", constraint=models.UniqueConstraint(fields=("row", "attempt_number"), name="int_pay_attempt_row_number_uniq")),
        migrations.AddConstraint(model_name="salarypaymentattempt", constraint=models.CheckConstraint(condition=Q(attempt_number__gt=0), name="int_pay_attempt_number_positive")),
        migrations.AddConstraint(model_name="salarypaymentattempt", constraint=models.CheckConstraint(condition=Q(status__in=["processing", "paid", "failed", "reversed"]), name="int_pay_attempt_status_valid")),
        migrations.AddIndex(model_name="salarypaymentattempt", index=models.Index(fields=["company", "row", "attempt_number"], name="int_pay_attempt_row_idx")),
        migrations.AddConstraint(model_name="salarypaymentresultimport", constraint=models.UniqueConstraint(fields=("batch", "content_sha256"), name="int_pay_result_batch_hash_uniq")),
        migrations.AddIndex(model_name="salarypaymentresultimport", index=models.Index(fields=["company", "batch", "-imported_at"], name="int_pay_result_batch_idx")),
    ]
